name: Docker Image CI

on: workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: |
         echo "$[{ secrets.DOCKERPW }]" | docker login -u  "santhosh955" --password-stdin
         docker image build -t santhosh955/javaapp:v1 .
	 docker push santhosh955/javaapp:v1

